def calculate_environmental_impact(yearly_generation_kwh, years=10):
    """
    Calculates the environmental benefits of the generated solar energy over a given timeframe.
    
    Args:
        yearly_generation_kwh (float): Energy generated by solar system in a year.
        years (int): Over how many years to calculate lifetime impact.
        
    Returns:
        dict: A dictionary containing various environmental metrics.
    """
    lifetime_generation = yearly_generation_kwh * years
    
    # Approx 0.85 kg of CO2 avoided per kWh
    co2_avoided_kg = lifetime_generation * 0.85
    co2_avoided_tons = co2_avoided_kg / 1000.0
    
    # 1 matured tree absorbs ~21 kg of CO2 annually
    # We estimate tree equivalents based on total CO2 avoided
    trees_planted_equivalent = co2_avoided_kg / 21.0
    
    # Avg passenger car emits ~0.40 kg CO2 / mile
    car_miles_avoided = co2_avoided_kg / 0.40
    
    return {
        "lifetime_generation_kwh": round(lifetime_generation, 2),
        "co2_avoided_kg": round(co2_avoided_kg, 2),
        "co2_avoided_tons": round(co2_avoided_tons, 2),
        "trees_planted": int(trees_planted_equivalent),
        "car_miles_avoided": round(car_miles_avoided, 2)
    }
